    - name: "Cleanup: Get list of all files object files in application directory: {{ springboot_deploy_folder }}"
      find:
        path: "{{ springboot_deploy_folder }}"
        recurse: no
      register: all_objects
      
    - name: "Cleanup: Clean application directory: {{ springboot_deploy_folder }}"
      file:
        path: "{{ item.path }}"
        state: absent
        recurse: no
      with_items: "{{ all_objects.files }}"
      when: item.path not in keep_these
  
