    - name: "Configure: Create systemd service file"
      template:
        src: app.service.j2
        dest: "{{ sysd_script }}"
        mode: 0644
        owner: "{{ springboot_user }}"
        group: "{{ springboot_group }}"
      become: yes

    - name: "Startup: Restart application"
      systemd:
        name: "{{ artifactid }}"
        enabled: yes
        daemon-reload: yes
        state: restarted
      become: yes