    - name: "Retrieve artifact and deploy application in application directory"
      maven_artifact:
        artifact_id: "{{ artifactid }}"
        group_id: "{{ groupid }}"
        version: "{{ version }}"
        dest: "{{ springboot_deploy_folder }}"
        repository_url: "{{ nexus_url }}/repository/snapshots/"
        state: "present"
        mode: 0644
        verify_checksum: always
        owner: "{{ ansible_user_id }}"
      become: yes
